### ISSUE TITLE
Tarea Infografía Matemáticas Discretas 

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/infografia-Eddi3mendoz#1]
[MÁTEMATICAS DISCRETAS.pdf](https://github.com/user-attachments/files/16766756/MATEMATICAS.DISCRETAS.pdf)

Elaborado por Edwin Eduardo Mendoza Cruz.

**Comment by ANGELGARCIASAN** [comment]
Redacción y ortografía: 14/14
Exposición de ideas centrales: 16/16
Organización de ideas centrales: 14/14
Uso de imágenes y colores: 13/14
Presentación visual: 14/14
Referencias : 14/14  
Calificacion final : 19.8
Calificó: Luis Angel García Santiago

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
